const prisma = require("../../configs/config");

const seedNutritionfactProducts = async () => {
  await prisma.nutritionFact.createMany({
    data: [
      {
        id: 1,
        energy: 200,
        saturated_fat: 1.5,
        sugar: 4,
        sodium: 0.28,
        protein: 6,
        fiber: 0,
        fruit_vegetable: 0,
      },
      {
        id: 2,
        energy: 150,
        saturated_fat: 2.5,
        sugar: 4,
        sodium: 0.125,
        protein: 3,
        fiber: 0,
        fruit_vegetable: 0,
      },
      {
        id: 3,
        energy: 350,
        saturated_fat: 5,
        sugar: 19,
        sodium: 0.29,
        protein: 8,
        fiber: 0,
        fruit_vegetable: 0,
      },
      {
        id: 4,
        energy: 210,
        saturated_fat: 4,
        sugar: 0.21,
        sodium: 0,
        protein: 9,
        fiber: 0,
        fruit_vegetable: 0,
      },
      {
        id: 5,
        energy: 150,
        saturated_fat: 5,
        sugar: 0,
        sodium: 0.71,
        protein: 13,
        fiber: 0,
        fruit_vegetable: 0,
      },
      {
        id: 6,
        energy: 100,
        saturated_fat: 2.5,
        sugar: 0,
        sodium: 0.08,
        protein: 1,
        fiber: 0,
        fruit_vegetable: 0,
      },
      {
        id: 7,
        energy: 350,
        saturated_fat: 5,
        sugar: 19,
        sodium: 0.29,
        protein: 8,
        fiber: 0,
        fruit_vegetable: 0,
      },
      {
        id: 8,
        energy: 130,
        saturated_fat: 1.5,
        sugar: 3,
        sodium: 0.135,
        protein: 3,
        fiber: 0,
        fruit_vegetable: 0,
      },
      {
        id: 9,
        energy: 90,
        saturated_fat: 1.5,
        sugar: 10,
        sodium: 0.105,
        protein: 7,
        fiber: 0,
        fruit_vegetable: 0,
      },
      {
        id: 10,
        energy: 160,
        saturated_fat: 4,
        sugar: 24,
        sodium: 0.04,
        protein: 1,
        fiber: 3,
        fruit_vegetable: 0,
      },
      {
        id: 11,
        energy: 45,
        saturated_fat: 4,
        sugar: 12,
        sodium: 0.015,
        protein: 0,
        fiber: 0,
        fruit_vegetable: 0,
      },
    ],
  });
};

module.exports = { seedNutritionfactProducts };
